// src/app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";

export const metadata = {
	title: "Golden Matcha",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<head>
				{/* Google Site Verification */}
				<meta name="google-site-verification" content="a28835f912cf49f6" />
			</head>
			<body>{children}</body>
		</html>
	);
}
